name: CD

on:
  push:
    branches: [main]

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          version=$(xmllint --xpath "string(//project/version)" pom.xml)
          echo "app_version=${version}" >> $GITHUB_ENV

  docker:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            danilopedrazzi/elderly-api:latest
            danilopedrazzi/elderly-api:${{ env.app_version }}

  create-release:
    runs-on: ubuntu-latest
    needs: [get-version, docker]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get latest commit message
        id: get_commit_message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "::set-output name=commit_message::${commit_message}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.app_version }}
          release_name: Release ${{ env.app_version }}
          body: ${{ steps.get_commit_message.outputs.commit_message }}
          draft: false
          prerelease: false