name: CD

on:
  push:
    branches: [main]

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: get-version
        id: pom-version
        uses: PERES-Richard/maven-get-version-action@v3.0.0

      - name: Insert version into environment
        run: echo "APP_VERSION=${{ steps.pom-version.outputs.version }}" >> $GITHUB_ENV

  docker:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            danilopedrazzi/elderly-api:latest
            danilopedrazzi/elderly-api:${{ env.APP_VERSION }}

  create-release:
    runs-on: ubuntu-latest
    needs: [get-version, docker]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get latest commit message
        id: get_commit_message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "::set-output name=commit_message::${commit_message}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.APP_VERSION }}
          release_name: Release ${{ env.APP_VERSION }}
          body: ${{ steps.get_commit_message.outputs.commit_message }}
          draft: false
          prerelease: false