name: Deploy Pipeline

on:
  push:
    branches:
      - main
      - dev
      - deploy-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Maven
      run: |
        chmod +x ./mvnw
        ./mvnw clean package -DskipTests

    - name: Upload file to Public EC2
      env:
        PUBLIC_EC2_IP: ${{ secrets.PUBLIC_EC2_IP }}
        JUMP_HOST_USER: ${{ secrets.JUMP_HOST_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H $PUBLIC_EC2_IP >> ~/.ssh/known_hosts
        scp -i ssh_key.pem /home/runner/work/BackEnd/BackEnd/target/elder-ly-1.0.jar ${JUMP_HOST_USER}@${PUBLIC_EC2_IP}:/home/${JUMP_HOST_USER}/
        scp -i ssh_key.pem /home/runner/work/BackEnd/BackEnd/start.sh ${JUMP_HOST_USER}@${PUBLIC_EC2_IP}:/home/${JUMP_HOST_USER}/

    - name: Transfer file from Public EC2 to Private EC2 and start app
      env:
        PRIVATE_EC2_IP: ${{ secrets.PRIVATE_EC2_IP }}
        PUBLIC_EC2_IP: ${{ secrets.PUBLIC_EC2_IP }}
        JUMP_HOST_USER: ${{ secrets.JUMP_HOST_USER }}
        PRIVATE_HOST_USER: ${{ secrets.PRIVATE_HOST_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh-keyscan -H $PUBLIC_EC2_IP >> ~/.ssh/known_hosts
        ssh -i ssh_key.pem ${JUMP_HOST_USER}@${PUBLIC_EC2_IP} << 'EOF_JUMP'
          scp -i Elderly.pem elder-ly-1.0.jar ${PRIVATE_HOST_USER}@${PRIVATE_EC2_IP}:/home/${PRIVATE_HOST_USER}/
          scp -i Elderly.pem start.sh ${PRIVATE_HOST_USER}@${PRIVATE_EC2_IP}:/home/${PRIVATE_HOST_USER}/
          ssh -t -i Elderly.pem ${PRIVATE_HOST_USER}@${PRIVATE_EC2_IP} << 'EOF_PRIVATE'
            pkill -f 'java -jar' || echo "No running instance found"
            chmod +x start.sh
            ./start.sh
          EOF_PRIVATE
        EOF_JUMP
